PROGS_HARDESTGAME_OBJS := hardestGame.o
PROGS_HARDESTGAME_OBJS := $(PROGS_HARDESTGAME_OBJS:%=$(TDIR)/hardestGame/%)
ALL_OBJS += $(PROGS_HARDESTGAME_OBJS)

$(TDIR)/bin/hardestGame : $(TSTART) $(PROGS_HARDESTGAME_OBJS) $(TLIBC)

